name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.org"
      - "doc/"

defaults:
  run:
    shell: bash

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14 # this is arm64
          - ubuntu-24.04
          - windows-2022
        emacs-version: ["25.1", "26.3", "27.2", "28.2", "29.3"]
        # purcell/setup-emacs does not provide old Emacs versions for macos 14
        # (likely for good reason)
        exclude:
          - os: macos-14
            emacs-version: "25.1"
          - os: macos-14
            emacs-version: "26.3"
          - os: macos-14
            emacs-version: "27.2"
          - os: windows-2022
            # TLS fails to load in this version on Windows
            emacs-version: "25.1"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # - name: SSH access for debug
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true
      #     limit-access-to-actor: true
      - name: Set up Rust
        run: rustup install stable
      - name: Set up Emacs
        if: runner.os != 'Windows'
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - name: Set up Emacs
        if: runner.os == 'Windows'
        uses: jcs090218/setup-emacs-windows@master
        with:
          version: ${{ matrix.emacs-version }}
      - name: Set up Cask
        uses: cask/setup-cask@master
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
          export PATH="$HOME/.cask/bin:$PATH"
          make test
