name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.org"
      - "doc/"

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14 # this is arm64
          - ubuntu-24.04
          - windows-2022
        emacs-version: ["25.1", "26.3", "27.2", "28.2", "29.3"]
        # purcell/setup-emacs does not provide old Emacs versions for macos 14
        # (likely for good reason)
        exclude:
          - os: macos-14
            emacs-version: "25.1"
          - os: macos-14
            emacs-version: "26.3"
          - os: macos-14
            emacs-version: "27.2"
          - os: windows-2022
            # TLS fails to load in this version on Windows
            emacs-version: "25.1"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: SSH access for debug
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          limit-access-to-actor: true
      - name: Set up Rust
        run: rustup install stable
      - name: Set up Emacs
        if: runner.os != 'Windows'
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - name: Set up Emacs
        if: runner.os == 'Windows'
        uses: jcs090218/setup-emacs-windows@master
        with:
          version: ${{ matrix.emacs-version }}
      # Remove expired DST Root CA X3 certificate. Workaround for
      # https://debbugs.gnu.org/cgi/bugreport.cgi?bug=51038 bug on Emacs 27.2.
      # https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-1126671598
      #
      # Copied from https://github.com/emacs-tree-sitter/elisp-tree-sitter/blob/master/.github/workflows/main.yml#L62
      - name: Workaround for Emacs 27.2's Windows build from GNU FTP
        if: ${{ runner.os == 'Windows' && matrix.emacs-version == '27.2' }}
        run: |
          gci cert:\LocalMachine\Root\DAC9024F54D8F6DF94935FB1732638CA6AD77C13
          gci cert:\LocalMachine\Root\DAC9024F54D8F6DF94935FB1732638CA6AD77C13 | Remove-Item
      - name: Set up Cask
        uses: cask/setup-cask@v1.1
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
          make test
